In [2]:
import numpy as np
from scipy.io import wavfile

In [4]:
data = np.full((128 * 5), 5000)

In [8]:
np.full((10, 1), 5)

array([[5],
       [5],
       [5],
       [5],
       [5],
       [5],
       [5],
       [5],
       [5],
       [5]])

In [11]:
wavfile.write('something.wav', 44100, np.full((44100 * 5, 1), 5000))

In [42]:
wavfile.write('foo.wav', 44100, np.random.uniform(0, 32767, (40000, 1)).astype('int16'))

In [39]:
data = np.linspace(-32767, 32767, 44100 * 5).reshape(44100 * 5, 1).astype('int16')

In [56]:
wavfile.write('foo.wav', 44100, data)

In [62]:
wavfile.write('foo.wav', 44100, np.random.uniform(230, 255, data.shape).astype('int8'))

In [68]:
sampling_rate = 44100


def seno(frequency, duration=2, sampling_rate=44100.0):
    return np.array([np.sin(n * 2 * np.pi * frequency / sampling_rate) for n in range(int(duration * sampling_rate))]).reshape(-1, 1)

# Example:
wavfile.write('ejemplo_seno.wav', sampling_rate, seno(1000).astype('int16'))

In [59]:
np.random.uniform(0, 255, data.shape).astype('int8')

array([[   1],
       [ -25],
       [ -96],
       ...,
       [ -11],
       [ 103],
       [-116]], dtype=int8)

In [54]:
np.random.uniform(-32767, 32767, data.shape).astype('int16')

array([[-20140],
       [ 20797],
       [  9422],
       ...,
       [ 18560],
       [ -9107],
       [-12682]], dtype=int16)

In [70]:
import numpy as N
import wave

class SoundFile:
   def  __init__(self, signal):
       self.file = wave.open('test.wav', 'wb')
       self.signal = signal
       self.sr = 44100

   def write(self):
       self.file.setparams((1, 2, self.sr, 44100*4, 'NONE', 'noncompressed'))
       self.file.writeframes(self.signal)
       self.file.close()

# let's prepare signal
duration = 4 # seconds
samplerate = 44100 # Hz
samples = duration*samplerate
frequency = 440 # Hz
period = samplerate / float(frequency) # in sample points
omega = N.pi * 2 / period

xaxis = N.arange(int(period),dtype = N.float) * omega
ydata = 16384 * N.sin(xaxis)

signal = N.resize(ydata, (samples,))

ssignal = ''
for i in range(len(signal)):
   ssignal += wave.struct.pack('h',signal[i]) # transform to binary

f = SoundFile(ssignal)
f.write()
print('file written')

error: required argument is not an integer